### ISSUE TITLE
Add put method (or flag to open) where kastore neither copies or takes ownership of the buffer.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/kastore#180]
#179 Added the ability of callers to take ownership of arrays that have been created and read by kastore, thereby avoiding a copy.
I would be possible to do this in reverse and allow kastore to take ownership of arrays that are being written.

I can imagine this only being useful in tskit when the `tsk_table_collection` dump is the last thing done to that `tsk_table_collection`, as it would no longer own its arrays.

**Comment by jeromekelleher** [comment]
Turns out we already have this in the [own put](https://github.com/tskit-dev/kastore/blob/86c03bca325430c5e381ffb87ff494230309aa84/c/kastore.h#L487) operation.

What's probably more useful from tskit's perspective though is kastore "borrowing" the buffer - **dont** take a copy and don't claim ownership. I think this would work in tskit because we're sure that the buffers will remain valid between the call to kastore_open [here](https://github.com/tskit-dev/tskit/blob/1e73968d1bdf96815c20ad9459f53b1c19bdda2b/c/tskit/tables.c#L10787) and when kastore_close is called.

That would mean we can avoid another copy of the tables when writing out, right?

**Comment by benjeffery** [comment]
I'd had this exact thought with AFK at the fish and chip shop, as long as the caller guarantees the lifetime of the buffers is longer than that of the kastore then we can avoid the copy. Will edit title to reflect.

**Comment by benjeffery** [comment]
The question then is if this is a flag to open, or a new set of put methods. I would argue for a flag, as it is the whole kastore's lifecycle that you need to manage even if you called a new put method on one array.

**Comment by jeromekelleher** [comment]
Hmm, let's see.

[kastore_put](https://github.com/tskit-dev/kastore/blob/86c03bca325430c5e381ffb87ff494230309aa84/c/kastore.c#L829)  takes the array as a ``const void *`` and has an options argument, so we could pass in a borrowed pointer there along with ``KAS_BORROW_ARRAY`` (or something) without issues.

The issue though is that the [array field](https://github.com/tskit-dev/kastore/blob/a266c6d53a24db613dfbfdbe89b34c274c8c6272/c/kastore.h#L193) in the ka_item struct is *not* const, so we couldn't assign it in there.

So, I think we'd have to change things a bit so that we'd have something like
```c
typedef struct {
    int type;
    size_t key_len;
    size_t array_len;
    char *key;
    void *array;
    /* Used instead of ``array`` when we ``put`` an item where the key buffer memory is 
       owned by the client */
    const void *borrowed_array;
    size_t key_start;
    size_t array_start;
} kaitem_t;
```

It's not very elegant, but we could make it work?

**Comment by benjeffery** [comment]
Hmm, seems to be the only way unless you added it as an extra out method. Worth a try I think.
